name: GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'  # 如果您将构建输出到 docs 目录，防止无限循环

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 设置 Ruby 环境
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # 或者您需要的 Ruby 版本

      - name: 安装依赖
        run: |
          gem install bundler
          bundle install

      - name: 构建网站
        run: bundle exec jekyll build

      - name: 部署到 GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

      - name: 部署
        uses: actions/deploy-pages@v1
