name: GitHub Pages

on:
  push:
    branches: # 部署分支
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      - name: install dependencies
        run: |
          gem install bundler
          bundle install

      - name: build
        run: bundle exec jekyll build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site